SELECT * FROM customer LIMIT 20

--1. Total revenue generated by male vs female customers.
SELECT gender, SUM(purchase_amount_usd) AS revenue_generated
FROM customer 
GROUP BY gender

--2. Customers who applied discount but still spent more than average.
SELECT customer_id, purchase_amount_usd FROM customer 
WHERE discount_applied = 'Yes'
AND purchase_amount_usd > 
(SELECT AVG(purchase_amount_usd) FROM customer)

--3. Top 5 products with highest average review rating.
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) 
AS average_review_rating
FROM customer GROUP BY item_purchased
ORDER BY average_review_rating DESC LIMIT 5

SELECT item_purchased, 
ROUND(AVG(CAST(review_rating AS NUMERIC)), 2) 
AS average_review_rating
FROM customer GROUP BY item_purchased
ORDER BY average_review_rating DESC LIMIT 5

--4. Compare average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount_usd), 2)
AS average_purchase
FROM customer WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type

--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS total_customers, 
ROUND(AVG(purchase_amount_usd), 2) AS average_spend, ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer GROUP BY subscription_status ORDER BY total_revenue, average_spend DESC

--6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5

--7. Segment customers into New, Returning and Loyal based on previous purchases and show count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases IN (0,1) THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers FROM customer_type GROUP BY customer_segment

--8. 3 most purchased products within each category.
WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders FROM item_counts WHERE item_rank <= 3

--9. Are repeat customers (>5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(*) AS repeat_buyers 
FROM customer WHERE previous_purchases > 5 GROUP BY subscription_status

--10. Revenue contribution of each age group.
SELECT age_group, SUM(purchase_amount_usd) AS revenue_generated 
FROM customer GROUP BY age_group ORDER BY revenue_generated DESC